
server:
  port: 8088
logging:
  level:
    com.nbclass: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fianl?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2: 
      min-idle: 5 
      initial-size: 5 
      max-total: 5
      max-wait-millis: 200
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  jpa:
      hibernate:
        ddl-auto: update
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:F:/My/fianl/src/main/resources/static/
      
      
